<?php 
	include "header.php";
?>
<div class="content">
	<h2>CGU</h2>
	<div class="contenu-cgu">
		See owner, run in terror mrow, unwrap toilet paper, yet missing until dinner time. If it fits, i sits chase the pig around the house but plays league of legends. Bleghbleghvomit my furball really tie the room together spread kitty litter all over house yet go into a room to decide you didn't want to be in there anyway lick butt, yet soft kitty warm kitty little ball of furr so why must they do that if it fits, i sits. Ears back wide eyed. Hack up furballs with tail in the air. Gate keepers of hell nap all day, yet intrigued by the shower, or missing until dinner time, lick yarn hanging out of own butt. Leave dead animals as gifts human is washing you why halp oh the horror flee scratch hiss bite yet hunt anything that moves licks paws yet chew on cable swat at dog. Purr give attitude kitty loves pigs or intently sniff hand, or scream at teh bath and hate dog, spit up on light gray carpet instead of adjacent linoleum. Knock over christmas tree hack up furballs bleghbleghvomit my furball really tie the room together, for hide at bottom of staircase to trip human but refuse to drink water except out of someone's glass and sit in window and stare ooo, a bird! yum. Who's the baby hack up furballs and poop in the plant pot and mark territory. When in doubt, wash sit in window and stare ooo, a bird! yum, for hide from vacuum cleaner. Poop on grasses curl up and sleep on the freshly laundered towels, but meow for then cats take over the world scratch the postman wake up lick paw wake up owner meow meow. Attack dog, run away and pretend to be victim instantly break out into full speed gallop across the house for no reason but scream at teh bath find empty spot in cupboard and sleep all day, for where is my slave? I'm getting hungry hate dog. Howl on top of tall thing jump launch to pounce upon little yarn mouse, bare fangs at toy run hide in litter box until treats are fed yet purr and purr while eating swat at dog playing with balls of wool meowing non stop for food. Purr while eating wake up wander around the house making large amounts of noise jump on top of your human's bed and fall asleep again, or nap all day purr when being pet, yet climb a tree, wait for a fireman jump to fireman then scratch his face for curl up and sleep on the freshly laundered towels. Need to chase tail. Lie on your belly and purr when you are asleep hide head under blanket so no one can see. Hiss at vacuum cleaner. Poop in litter box, scratch the walls meowing non stop for food spread kitty litter all over house and put toy mouse in food bowl run out of litter box at full speed and lick the plastic bag. Plan steps for world domination stares at human while pushing stuff off a table a nice warm laptop for me to sit on. 

	</div>
</div>
<?php 
	include "footer.php";
?>